version: '3.8'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: youruser
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: my_mongo_express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: youruser
      ME_CONFIG_MONGODB_ADMINPASSWORD: yourpassword
    ports:
      - "8081:8081"
    depends_on:
      - "mongodb"
    restart: unless-stopped

    
# docker run -d --name mars_mongodb -v ./mongo_data:/data/db